# Generated by Django 5.2.3 on 2026-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_applicant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='destination_country',
        ),
        migrations.AddField(
            model_name='applicant',
            name='current_country_of_residence',
            field=models.CharField(blank=True, help_text='Current country where the applicant resides', max_length=100),
        ),
    ]
