# Generated by Django 5.2.3 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_remove_applicant_destination_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='current_country_of_residence',
        ),
        migrations.AddField(
            model_name='applicant',
            name='current_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
