# Generated by Django 5.2.3 on 2026-03-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_populate_china_visa_services'),
        ('documents', '0002_service_requirements'),
    ]

    operations = [
    ]
